### ISSUE TITLE
Instructor Notes

### ISSUE THREAD

**Issue by bartdorsey** [arkaneshiro/aircnc#1]
* Consider that Hosts might want to list multiple Kitchens
* In addition to being able to list a kitchen a host should be able to specify the availability of the kitchen.
* How do Hosts leave reviews for Users?
* Should users be able to search for kitchens instead of hosts by availability or location?
* Consider that Hosts do not need to search for Users, because they should be able to see which Users have tried to book their Kitchen and can review them at that time.
* Detail the process involved in booking a kitchen.
* Elaborate on how the availability of kitchen will work.
* For the Bonus messaging feature, consider that Users and Hosts should only be able to message if there is an active booking
* Add features to the list to explain how User registration and Login will work for both regular Users and Hosts. (and if those need to be different kinds of users or not) (Consider using role based authorization for Host and User roles)
* Explain what CNC stands for 😸

**Comment by bartdorsey** [comment]
Before I start reviewing this, I fixed your markdown on a few pages. Feel free to copy these over and commit them. 

```markdown
# Backend Routes

## Users

- POST /users - sign up
- PATCH /users/:id - edit user informations

## Session

- POST /session - log in
- DELETE /session - log out

## Kitchens

- GET /kitchens - returns all kitchens
- GET /kitchens/search - returns matching kitchens by query params (city, features etc)
- GET /kitchens/:id - returns a particular kitchen
- GET /users/:id/kitchens - returns all of a hosts kitchens
- POST /kitchens - create a kitchen
- DELETE /kitchens/:id - delete a kitchen

## Bookings

- POST /kitchens/:id - guest creates a booking
- GET /users/:id/bookings - returns all of a guests bookings
- GET /bookings/:id - returns a particular booking
- PATCH /bookings/:id - a guest / host cancels a particular booking
- GET /kitchens/:id/bookings - returns all bookings for a particular kitchen
- GET /users/:id/kitchens/bookings - returns all of a hosts bookings

## Reviewing

- GET /kitchens/:id/reviews - returns all reviews for a particular kitchen
- GET /users/:id/reviews - returns all reviews for a particular guest
- POST /kitchens/:id/reviews - guest creates a review for a kitchen
- POST /users/:id/reviews - host creates a review for a guest
```

```markdown
# aircnc

## Air Cuisine & Cooking

a site to rent brilliant, incredible, amazing, show stopping, spectacular, never the same, totally unique kitchens

## Bookings

As a Host
I want to be able to list my kitchens
So that I can rent it

As a Host
I want to be able to confirm bookings by Users
so that I dont overbook myself or book users who I wouldn't like to use my kitchen

As a User
I want to be able to confirm bookings easily
So that I can complete my kitchen plans

## Reviewing

As a Host
I want to be able to see reviews of Users who have attempted bookings in one of my kitchens
So that I can evaluate wether I would like to let them use my kitchen

As a User
I want to be able to see reviews of Hosts
So that I can evaluate wether I would like to use thier kitchen

As a user and a host
I would like to give the kitchen I rented a review
so that the host and user can recieve constructive feedback

## Searching

As a User
I want to search for kitchens around me
So that I can see a list of kitchens to rent

As a User
I want to search for hosts by date of availability
So that I can plan ahead and rent one when I travel

As a User
I want to search for kitchens by location
So that I can find a kitchen that is convinient to me

## Bonus

As a User or Host
I would like to be able to message other users or hosts
So that I can

```

You frontend routes aren't so easy to format so I didn't do those....

**Comment by bartdorsey** [comment]
# Backend Routes

## Users

- PATCH /users/:id -- This should be a PUT request
- I would recommend you use JWT instead of sessions, this means you would end
  up with the following routes
  - POST /users/token - Login
  - Logout would just be deleting the token from localStorage and redirecting to `/`

## Kitchens

- GET /kitchens/search -- This should be a POST if you are querying on more than
  one field.  Generally we only use GET for simple single field search.

## Bookings

- POST /kitchens/:id - This should be POST /kitchens/:id/bookings since bookings
  is the resource you are creating.
- PATCH /bookings/:id - This should either be a PUT if you are updating the
  booking, or a DELETE if you are just destroying the booking.
- GET /users/:id/kitchens/bookings - This probably should not exist, but it all
  depends on how your 'Bookings' model works.  We might need to discuss this
  further once you finish designing your Models. In fact I would recommend
  getting your Model design done first in the future, as this will make it
  easier to figure out what routes you need. I would revisit all the routes
  once you have the Models designed.

## Reviewing

- These all look good.

**Comment by bartdorsey** [comment]
# Frontend Routes

I'm a little confused about why the routes are indented?

- /listings - Shouldn't this just be /kitchens?
- /listings/<something> - If this is a search page, the it should probably be
  /kitchens/search. This should be thought of as the 'advanced search'. A 
  simple search could be done by having a search right on the front page `/`
- /listings/:id - This should probably be /kitchens/:id
- /listings/checkout - This could probably be just /checkout. Was this in your
  feature list? I don't remember seeing any details about checking out.
- /profile - Is this the user's profile? It should be /users/:id/profile then
- /bookings/:id - This seems fine but the indentation makes me think this is 
  under /profile which seems strange and unnecessary to me.
- /review - it seems if they are leaving reviews for a host, it would just be
  a route that explains this. /users/:id/review
- /bookings/:id/review - If the review is for a guest, then it's just a user
  review and can use the same page /users/:id/review. If there is a need to have
  separate forms for reviewing hosts vs users, then make one prefix /users and
  the other one /hosts
    - /users/:id/review
    - /hosts/:id/review
- /create-listing - Probably just /kitchens/create

I think you should definitely revisit these and make them align better with the
names you are using on the backend API. It'll make your code easier to under
stand. I would also try to use correct markdown so this is a bit easier to
read and understand.

**Comment by arkaneshiro** [comment]
Thanks for the feedback! We've added an image showing what our models will look like, and we've made some adjustments following your suggestions with naming conventions and HTML Requests.
